### ISSUE TITLE
MC crashes in offline mode without internet

### ISSUE THREAD

**Issue by Slooshie1** [chloecdn/Essentials#1]
Even when this is the only mod loaded aside from QFAPI+QSL (Quilted Fabric API + Quilt Standard Libraries) Minecraft fails to launch in offline mode if I turn off Wi-Fi and Ethernet so that I'm not connected to the internet. here is my latest.log, uploaded using Prism Launcher: https://mclo.gs/W4XbBpn

**Comment by chloecdn** [comment]
It's an issue with the Updater. On startup, it'll check my repo for the latest version, which it obviously cannot.
I will remove the Updater because it's kinda buggy anyway, and then it should work again.
Just check the Releases-Section in a few hours.

**Comment by chloecdn** [comment]
Now updated. 
[1.2.2+1.19](https://github.com/chloecdn/Essentials/releases/tag/1.2.2%2B1.19)

Should be fixed now.
